# Generated by Django 3.1 on 2020-09-20 04:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('URLHandler', '0002_remove_shorturl_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shorturl',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
