# Generated by Django 3.1 on 2020-11-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_shorty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='short_url',
            old_name='originalURL',
            new_name='original_URL',
        ),
        migrations.RenameField(
            model_name='short_url',
            old_name='shortQuery',
            new_name='short_Query',
        ),
    ]
