# Generated by Django 3.1 on 2020-11-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_shorty', '0002_auto_20201101_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='short_url',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='short_url',
            name='updated_at',
        ),
    ]
